---
- name: Check if mongod is active
  shell: systemctl status mongod
  changed_when: true
  register: mongo_status
  ignore_errors: true

- name: Get mongo service status
  debug:
    msg: "{{ mongo_status }}"

- name: Enter the mongo shell
  community.mongodb.mongodb_shell:
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    eval: 'db.adminCommand( { replSetGetStatus: 1, initialSync: 1 } )'
    stringify: yes
  register: replica_set_status
  when: mongo_status is succeeded

- name: Get replica set status
  debug:
    msg: "{{ replica_set_status }}"
