---
- name: Changing current primary node to secondary node
  community.mongodb.mongodb_shell:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      eval: 'db.adminCommand( { replSetStepDown: 120, secondaryCatchUpPeriodSecs: 15 } )'
      stringify: yes
  register: replica_stepdown_status
  ignore_errors: true

- name: Get replication status
  debug:
    msg: "{{ replica_stepdown_status }}"

- name: Checking the cluster health
  community.mongodb.mongodb_shell:
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    eval: 'db.adminCommand( { replSetGetStatus: 1, initialSync: 1 } )'
    stringify: yes
  register: replica_set_status
  when: replica_stepdown_status is succeeded

- name: Get replication set status
  debug:
    msg: "{{ replica_set_status }}"

- name: Stopping mongo service
  community.mongodb.mongodb_shell:
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    eval: 'db.adminCommand({ "shutdown" : 1, timeoutSecs: 60 })'
    stringify: yes
  register: mongo_service_stop
  when: replica_set_status is succeeded
  ignore_errors: true

- name: Get Mongo service status
  debug:
    msg: "{{ mongo_service_stop }}"
